Shaders/src/dummy.vert
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 71

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 43 55 67
                              Source GLSL 450
                              Name 4  "main"
                              Name 12  "positions"
                              Name 23  "colors"
                              Name 31  "pUVs"
                              Name 41  "gl_PerVertex"
                              MemberName 41(gl_PerVertex) 0  "gl_Position"
                              MemberName 41(gl_PerVertex) 1  "gl_PointSize"
                              MemberName 41(gl_PerVertex) 2  "gl_ClipDistance"
                              MemberName 41(gl_PerVertex) 3  "gl_CullDistance"
                              Name 43  ""
                              Name 47  "UniformBufferObject"
                              MemberName 47(UniformBufferObject) 0  "View"
                              MemberName 47(UniformBufferObject) 1  "Projection"
                              MemberName 47(UniformBufferObject) 2  "ViewProjection"
                              Name 49  "GfScene"
                              Name 55  "gl_VertexIndex"
                              Name 67  "uvs"
                              MemberDecorate 41(gl_PerVertex) 0 BuiltIn Position
                              MemberDecorate 41(gl_PerVertex) 1 BuiltIn PointSize
                              MemberDecorate 41(gl_PerVertex) 2 BuiltIn ClipDistance
                              MemberDecorate 41(gl_PerVertex) 3 BuiltIn CullDistance
                              Decorate 41(gl_PerVertex) Block
                              MemberDecorate 47(UniformBufferObject) 0 ColMajor
                              MemberDecorate 47(UniformBufferObject) 0 Offset 0
                              MemberDecorate 47(UniformBufferObject) 0 MatrixStride 16
                              MemberDecorate 47(UniformBufferObject) 1 ColMajor
                              MemberDecorate 47(UniformBufferObject) 1 Offset 64
                              MemberDecorate 47(UniformBufferObject) 1 MatrixStride 16
                              MemberDecorate 47(UniformBufferObject) 2 ColMajor
                              MemberDecorate 47(UniformBufferObject) 2 Offset 128
                              MemberDecorate 47(UniformBufferObject) 2 MatrixStride 16
                              Decorate 47(UniformBufferObject) Block
                              Decorate 49(GfScene) DescriptorSet 0
                              Decorate 49(GfScene) Binding 0
                              Decorate 55(gl_VertexIndex) BuiltIn VertexIndex
                              Decorate 67(uvs) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 2
               8:             TypeInt 32 0
               9:      8(int) Constant 6
              10:             TypeArray 7(fvec2) 9
              11:             TypePointer Private 10
   12(positions):     11(ptr) Variable Private
              13:    6(float) Constant 3204448256
              14:    6(float) Constant 1056964608
              15:    7(fvec2) ConstantComposite 13 14
              16:    7(fvec2) ConstantComposite 14 14
              17:    7(fvec2) ConstantComposite 14 13
              18:    7(fvec2) ConstantComposite 13 13
              19:          10 ConstantComposite 15 16 17 17 18 15
              20:             TypeVector 6(float) 3
              21:             TypeArray 20(fvec3) 9
              22:             TypePointer Private 21
      23(colors):     22(ptr) Variable Private
              24:    6(float) Constant 1065353216
              25:    6(float) Constant 0
              26:   20(fvec3) ConstantComposite 24 25 25
              27:   20(fvec3) ConstantComposite 25 24 25
              28:   20(fvec3) ConstantComposite 25 25 24
              29:   20(fvec3) ConstantComposite 24 24 25
              30:          21 ConstantComposite 26 27 28 28 26 29
        31(pUVs):     11(ptr) Variable Private
              32:    6(float) Constant 1073741824
              33:    7(fvec2) ConstantComposite 25 32
              34:    7(fvec2) ConstantComposite 32 32
              35:    7(fvec2) ConstantComposite 32 25
              36:    7(fvec2) ConstantComposite 25 25
              37:          10 ConstantComposite 33 34 35 35 36 33
              38:             TypeVector 6(float) 4
              39:      8(int) Constant 1
              40:             TypeArray 6(float) 39
41(gl_PerVertex):             TypeStruct 38(fvec4) 6(float) 40 40
              42:             TypePointer Output 41(gl_PerVertex)
              43:     42(ptr) Variable Output
              44:             TypeInt 32 1
              45:     44(int) Constant 0
              46:             TypeMatrix 38(fvec4) 4
47(UniformBufferObject):             TypeStruct 46 46 46
              48:             TypePointer Uniform 47(UniformBufferObject)
     49(GfScene):     48(ptr) Variable Uniform
              50:     44(int) Constant 2
              51:             TypePointer Uniform 46
              54:             TypePointer Input 44(int)
55(gl_VertexIndex):     54(ptr) Variable Input
              57:             TypePointer Private 7(fvec2)
              64:             TypePointer Output 38(fvec4)
              66:             TypePointer Output 7(fvec2)
         67(uvs):     66(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
                              Store 12(positions) 19
                              Store 23(colors) 30
                              Store 31(pUVs) 37
              52:     51(ptr) AccessChain 49(GfScene) 50
              53:          46 Load 52
              56:     44(int) Load 55(gl_VertexIndex)
              58:     57(ptr) AccessChain 12(positions) 56
              59:    7(fvec2) Load 58
              60:    6(float) CompositeExtract 59 0
              61:    6(float) CompositeExtract 59 1
              62:   38(fvec4) CompositeConstruct 60 61 25 24
              63:   38(fvec4) MatrixTimesVector 53 62
              65:     64(ptr) AccessChain 43 45
                              Store 65 63
              68:     44(int) Load 55(gl_VertexIndex)
              69:     57(ptr) AccessChain 31(pUVs) 68
              70:    7(fvec2) Load 69
                              Store 67(uvs) 70
                              Return
                              FunctionEnd
