Shaders/src/dummy.frag
// Module Version 10000
// Generated by (magic number): 80007
// Id's are bound by 20

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 17
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "outColor"
                              Name 13  "Albedo"
                              Name 17  "uvs"
                              Decorate 9(outColor) Location 0
                              Decorate 13(Albedo) DescriptorSet 0
                              Decorate 13(Albedo) Binding 0
                              Decorate 17(uvs) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
     9(outColor):      8(ptr) Variable Output
              10:             TypeImage 6(float) 2D sampled format:Unknown
              11:             TypeSampledImage 10
              12:             TypePointer UniformConstant 11
      13(Albedo):     12(ptr) Variable UniformConstant
              15:             TypeVector 6(float) 2
              16:             TypePointer Input 15(fvec2)
         17(uvs):     16(ptr) Variable Input
         4(main):           2 Function None 3
               5:             Label
              14:          11 Load 13(Albedo)
              18:   15(fvec2) Load 17(uvs)
              19:    7(fvec4) ImageSampleImplicitLod 14 18
                              Store 9(outColor) 19
                              Return
                              FunctionEnd
