Shaders/src/dummy.vert
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 29

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 10 22 27
                              Source GLSL 450
                              Name 4  "main"
                              Name 8  "gl_PerVertex"
                              MemberName 8(gl_PerVertex) 0  "gl_Position"
                              Name 10  ""
                              Name 14  "UniformBufferObject"
                              MemberName 14(UniformBufferObject) 0  "View"
                              MemberName 14(UniformBufferObject) 1  "Projection"
                              MemberName 14(UniformBufferObject) 2  "ViewProjection"
                              MemberName 14(UniformBufferObject) 3  "colour"
                              Name 16  "FDSceneParams"
                              Name 22  "i_Position"
                              Name 27  "v_Color"
                              MemberDecorate 8(gl_PerVertex) 0 BuiltIn Position
                              Decorate 8(gl_PerVertex) Block
                              MemberDecorate 14(UniformBufferObject) 0 ColMajor
                              MemberDecorate 14(UniformBufferObject) 0 Offset 0
                              MemberDecorate 14(UniformBufferObject) 0 MatrixStride 16
                              MemberDecorate 14(UniformBufferObject) 1 ColMajor
                              MemberDecorate 14(UniformBufferObject) 1 Offset 64
                              MemberDecorate 14(UniformBufferObject) 1 MatrixStride 16
                              MemberDecorate 14(UniformBufferObject) 2 ColMajor
                              MemberDecorate 14(UniformBufferObject) 2 Offset 128
                              MemberDecorate 14(UniformBufferObject) 2 MatrixStride 16
                              MemberDecorate 14(UniformBufferObject) 3 Offset 192
                              Decorate 14(UniformBufferObject) Block
                              Decorate 16(FDSceneParams) DescriptorSet 0
                              Decorate 16(FDSceneParams) Binding 0
                              Decorate 22(i_Position) Location 0
                              Decorate 27(v_Color) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
 8(gl_PerVertex):             TypeStruct 7(fvec4)
               9:             TypePointer Output 8(gl_PerVertex)
              10:      9(ptr) Variable Output
              11:             TypeInt 32 1
              12:     11(int) Constant 0
              13:             TypeMatrix 7(fvec4) 4
14(UniformBufferObject):             TypeStruct 13 13 13 7(fvec4)
              15:             TypePointer Uniform 14(UniformBufferObject)
16(FDSceneParams):     15(ptr) Variable Uniform
              17:     11(int) Constant 2
              18:             TypePointer Uniform 13
              21:             TypePointer Input 7(fvec4)
  22(i_Position):     21(ptr) Variable Input
              25:             TypePointer Output 7(fvec4)
     27(v_Color):     25(ptr) Variable Output
         4(main):           2 Function None 3
               5:             Label
              19:     18(ptr) AccessChain 16(FDSceneParams) 17
              20:          13 Load 19
              23:    7(fvec4) Load 22(i_Position)
              24:    7(fvec4) MatrixTimesVector 20 23
              26:     25(ptr) AccessChain 10 12
                              Store 26 24
              28:    7(fvec4) Load 22(i_Position)
                              Store 27(v_Color) 28
                              Return
                              FunctionEnd
