Shaders/src/dummy.frag
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 23

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 9 20
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "o_Color"
                              Name 11  "UniformBufferObject"
                              MemberName 11(UniformBufferObject) 0  "View"
                              MemberName 11(UniformBufferObject) 1  "Projection"
                              MemberName 11(UniformBufferObject) 2  "ViewProjection"
                              MemberName 11(UniformBufferObject) 3  "colour"
                              Name 13  "FDSceneParams"
                              Name 20  "v_Color"
                              Decorate 9(o_Color) Location 0
                              MemberDecorate 11(UniformBufferObject) 0 ColMajor
                              MemberDecorate 11(UniformBufferObject) 0 Offset 0
                              MemberDecorate 11(UniformBufferObject) 0 MatrixStride 16
                              MemberDecorate 11(UniformBufferObject) 1 ColMajor
                              MemberDecorate 11(UniformBufferObject) 1 Offset 64
                              MemberDecorate 11(UniformBufferObject) 1 MatrixStride 16
                              MemberDecorate 11(UniformBufferObject) 2 ColMajor
                              MemberDecorate 11(UniformBufferObject) 2 Offset 128
                              MemberDecorate 11(UniformBufferObject) 2 MatrixStride 16
                              MemberDecorate 11(UniformBufferObject) 3 Offset 192
                              Decorate 11(UniformBufferObject) Block
                              Decorate 13(FDSceneParams) DescriptorSet 0
                              Decorate 13(FDSceneParams) Binding 0
                              Decorate 20(v_Color) Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Output 7(fvec4)
      9(o_Color):      8(ptr) Variable Output
              10:             TypeMatrix 7(fvec4) 4
11(UniformBufferObject):             TypeStruct 10 10 10 7(fvec4)
              12:             TypePointer Uniform 11(UniformBufferObject)
13(FDSceneParams):     12(ptr) Variable Uniform
              14:             TypeInt 32 1
              15:     14(int) Constant 3
              16:             TypePointer Uniform 7(fvec4)
              19:             TypePointer Input 7(fvec4)
     20(v_Color):     19(ptr) Variable Input
         4(main):           2 Function None 3
               5:             Label
              17:     16(ptr) AccessChain 13(FDSceneParams) 15
              18:    7(fvec4) Load 17
              21:    7(fvec4) Load 20(v_Color)
              22:    7(fvec4) FMul 18 21
                              Store 9(o_Color) 22
                              Return
                              FunctionEnd
